# Generated by Django 5.2.7 on 2025-12-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
