# Generated by Django 5.2.7 on 2025-12-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_journaluser_last_entry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaluser',
            name='created_tags',
            field=models.JSONField(default=list),
        ),
    ]
