# Generated by Django 5.2.7 on 2025-12-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0003_journaluser_created_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journaluser',
            old_name='created_tags',
            new_name='tags',
        ),
    ]
